### ISSUE TITLE
Access level to oeGdprOptinOxcmp_user::_changeUser_noRedirect is wrong

### ISSUE THREAD

**Issue by leshatai** [OXID-eSales/gdpr-optin-module#1]
`
[18-May-2018 08:47:50 Europe/Berlin] 
PHP Fatal error:  Access level to oeGdprOptinOxcmp_user::_changeUser_noRedirect() must be public 
(as in class mo_empfaengerservices__oxcmp_user) in  
/modules/oe/gdproptin/components/oegdproptinoxcmp_user.php on line 0`

To fix, simply change to **public**. Affects Version 1.0.0 in Oxid-Version 4.10.6 PE with PHP 5.6.

**Comment by Sieg** [comment]
Hi @leshatai, As i see, we have it as protected in OxidEsales\EshopCommunity\Application\Component\UserComponent; Please give me more information how to reproduce the error. As i see, you have mentioned some mo_empfaengerservices__oxcmp_user class, which is not known to me. Consider checking that one first.

**Comment by leshatai** [comment]
@Sieg You are right. I had a look in the ``oxcpm_user`` class and in the one of the third-party-module ``mo_empfaengerservices__oxcmp_user`` and the module's declaration is plain wrong. Sorry, for the inconvience. You can close the issue.

The name of the said module is: **mo_empfaengerservices** with version **2.3.6**  just in case anyone stumbles across this issue.
