### ISSUE TITLE
module id and directory name mismatch?

### ISSUE THREAD

**Issue by vanilla-thunder** [OXID-eSales/gdpr-optin-module#2]
This issue is primary about b-1.x branch for oxid 4.10.
Shouldn't module id from metadata.php match module directory name?
Here the module id is "oegdproptin" but the directory is just "gdproptin".

There are some function using module id for filesystem path, like oxModule::getModulePath() generates module path with module id (basepath + 'modules/' + moduleId) when no database record is found, which would result in wrong path.

**Comment by Sieg** [comment]
Hi @vanilla-thunder, can you see the situation(please give the steps to reproduce), where the problem can appear in our case?

**Comment by Sieg** [comment]
Hello @vanilla-thunder, i have moved the issue to bugtrack, as we want to have them in one place. You can see the progress here: https://bugs.oxid-esales.com/view.php?id=6862
