### ISSUE TITLE
Newsletter agreement checkbox and gdpr opt-in checkbox are linked

### ISSUE THREAD

**Issue by herieth** [OXID-eSales/gdpr-optin-module#4]
Checking / Unchecking the newsletter checkbox or gdpr opt-in checkbox always dyes both labels green / default color. To the  registrant it looks like the acceptance is linked.

**Comment by Sieg** [comment]
Hello @herieth, i have moved the issue to bugtrack, as we want to have them in one place. You can see the progress here: https://bugs.oxid-esales.com/view.php?id=6864
